spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=1445
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}

jwt.SecretKey=${JWT_SECRET_KEY}